"use client"
import { useEffect, useState, useCallback } from "react"
import { useRouter } from "next/navigation"

const V="#8C3DFF", BLACK="#080808", OFF="#F4F1EB", MUT="rgba(244,241,235,.55)"
type Notif={id:string;type:string;title:string;body:string|null;link:string|null;read_at:string|null;created_at:string}
function seit(iso:string){const s=Math.floor((Date.now()-new Date(iso).getTime())/1000);if(s<60)return"gerade eben";if(s<3600)return`vor ${Math.floor(s/60)} Min`;if(s<86400)return`vor ${Math.floor(s/3600)} Std`;return`vor ${Math.floor(s/86400)} T`}

export default function NotificationBell({dark=false}:{dark?:boolean}){
 const router=useRouter(),[open,setOpen]=useState(false),[list,setList]=useState<Notif[]>([]),[unread,setUnread]=useState(0)
 const laden=useCallback(async()=>{try{const r=await fetch("/api/notifications",{cache:"no-store"});if(r.ok){const j=await r.json();setList(j.notifications||[]);setUnread(j.unread||0)}}catch{}},[])
 useEffect(()=>{laden();const t=setInterval(laden,30000);return()=>clearInterval(t)},[laden])
 async function read(n:Notif){if(!n.read_at){setList(v=>v.map(x=>x.id===n.id?{...x,read_at:new Date().toISOString()}:x));setUnread(v=>Math.max(0,v-1));try{await fetch("/api/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:n.id})})}catch{}}setOpen(false);if(n.link)router.push(n.link)}
 async function readAll(){setUnread(0);setList(v=>v.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));try{await fetch("/api/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})})}catch{}}
 const iconColor=dark?BLACK:OFF
 return <><button onClick={()=>setOpen(true)} aria-label="Benachrichtigungen" style={{position:"relative",width:38,height:38,border:`1px solid ${dark?"rgba(8,8,8,.16)":"rgba(244,241,235,.18)"}`,borderRadius:"50%",background:"transparent",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer",fontFamily:"inherit",flexShrink:0}}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke={iconColor} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/></svg>{unread>0&&<span style={{position:"absolute",top:-4,right:-4,minWidth:18,height:18,borderRadius:999,background:V,color:OFF,fontSize:10,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",padding:"0 4px"}}>{unread>9?"9+":unread}</span>}</button>
 {open&&<div onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.72)",zIndex:300,display:"flex",alignItems:"flex-end",justifyContent:"center"}}><div onClick={e=>e.stopPropagation()} style={{width:"100%",maxWidth:480,background:BLACK,borderTop:`2px solid ${V}`,maxHeight:"78vh",display:"flex",flexDirection:"column",boxShadow:"0 -20px 70px rgba(0,0,0,.55)"}}><div style={{padding:"20px 18px 15px",display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".18em",color:V,marginBottom:5}}>PLAYER</div><div style={{fontSize:25,fontWeight:900,color:OFF}}>Benachrichtigungen</div></div><button onClick={()=>setOpen(false)} style={{border:0,background:"none",color:OFF,fontSize:25,cursor:"pointer"}}>×</button></div>{unread>0&&<button onClick={readAll} style={{alignSelf:"flex-end",margin:"0 18px 10px",border:0,background:"transparent",color:V,fontWeight:800,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>ALLE GELESEN</button>}<div style={{overflowY:"auto"}}>{list.length===0?<div style={{color:MUT,padding:"36px 18px",fontSize:14}}>Noch keine Benachrichtigungen.</div>:list.map(n=><button key={n.id} onClick={()=>read(n)} style={{display:"block",width:"100%",textAlign:"left",padding:"14px 18px",background:n.read_at?"transparent":"rgba(140,61,255,.10)",border:0,borderTop:"1px solid rgba(244,241,235,.09)",cursor:"pointer",fontFamily:"inherit"}}><div style={{display:"flex",gap:9,alignItems:"flex-start"}}>{!n.read_at&&<span style={{width:7,height:7,borderRadius:"50%",background:V,marginTop:5,flexShrink:0}}/>}<div style={{flex:1}}><div style={{fontSize:14,fontWeight:800,color:OFF,lineHeight:1.25}}>{n.title}</div>{n.body&&<div style={{fontSize:12.5,color:"rgba(244,241,235,.68)",marginTop:4,lineHeight:1.4}}>{n.body}</div>}</div><span style={{fontSize:10.5,color:MUT,whiteSpace:"nowrap"}}>{seit(n.created_at)}</span></div></button>)}</div><button onClick={()=>{setOpen(false);router.push("/benachrichtigungen")}} style={{width:"100%",padding:"15px 18px",border:0,borderTop:"1px solid rgba(244,241,235,.12)",background:OFF,color:BLACK,fontWeight:900,fontFamily:"inherit",cursor:"pointer"}}>ALLE ANSEHEN →</button></div></div>}</>
}