"use client"
import { useState, useEffect } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase/client"

const C="#111111",B="#292929",W="#F4F1EB",M="rgba(244,241,235,.62)",V="#8C3DFF"
function Icon({d,fillBall}:{d:string;fillBall?:string}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={W} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" style={{marginRight:6,flexShrink:0}} dangerouslySetInnerHTML={{__html:d+(fillBall?`<circle cx="${fillBall}" fill="${W}" stroke="none"/>`:"")}}/>}
function buchenLink(){const basis="https://pingponglounge.ch/buchen?type=table&utm_source=player";try{const ort=typeof window!=="undefined"?window.localStorage.getItem("ppl_letzter_standort"):null;return ort?basis+"&location="+encodeURIComponent(ort):basis}catch{return basis}}
const row:React.CSSProperties={display:"flex",alignItems:"center",gap:4,padding:"13px 15px",borderTop:"1px solid #252525",textDecoration:"none"}
export default function StartMenu({name="Spieler",sub="",inline=false,avatar}:{name?:string;sub?:string;inline?:boolean;avatar?:string}){
 const[open,setOpen]=useState(false),[authed,setAuthed]=useState<boolean|null>(null);const router=useRouter();useEffect(()=>{let aktiv=true;createClient().auth.getUser().then(({data})=>{if(aktiv)setAuthed(!!data.user)});return()=>{aktiv=false}},[])
 async function logout(){await createClient().auth.signOut();router.push("/login")}
 const Link2=({href,label,icon}:{href:string;label:string;icon:React.ReactNode})=><Link href={href} style={row} onClick={()=>setOpen(false)}>{icon}<span style={{flex:1,fontSize:14,fontWeight:700,color:W}}>{label}</span><span style={{color:M,fontSize:13}}>›</span></Link>
 return <>{avatar?<button onClick={()=>setOpen(true)} aria-label="Profil & Menü" style={{...(inline?{position:"relative"}:{position:"absolute",top:18,right:16,zIndex:20}),width:40,height:40,borderRadius:"50%",border:`1px solid ${V}`,background:"transparent",color:W,fontSize:14,fontWeight:900,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}>{avatar}</button>:<button onClick={()=>setOpen(true)} aria-label="Menü" style={{...(inline?{position:"relative"}:{position:"absolute",top:18,right:16,zIndex:20}),background:"transparent",border:"1px solid rgba(244,241,235,.18)",borderRadius:"50%",width:40,height:40,display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke={W} strokeWidth="2" strokeLinecap="round"><path d="M5 7h14M5 12h14M5 17h14"/></svg></button>}
 {open&&<div onClick={()=>setOpen(false)} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.72)",zIndex:200,display:"flex",justifyContent:"flex-end"}}><div onClick={e=>e.stopPropagation()} style={{width:"86%",maxWidth:360,height:"100%",background:"#080808",borderLeft:`2px solid ${V}`,padding:"22px 16px",overflowY:"auto"}}><div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",marginBottom:22}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".18em",color:V}}>PPL. PLAYER</div><div style={{fontSize:27,fontWeight:900,color:W,marginTop:4}}>MENU.</div></div><button onClick={()=>setOpen(false)} aria-label="schliessen" style={{border:0,background:"none",color:W,fontSize:27,cursor:"pointer"}}>×</button></div>
 {authed?<Link href="/profil" onClick={()=>setOpen(false)} style={{display:"flex",alignItems:"center",gap:13,padding:"14px",background:C,textDecoration:"none",border:"1px solid rgba(244,241,235,.1)"}}><span style={{width:42,height:42,borderRadius:"50%",border:`1px solid ${V}`,display:"flex",alignItems:"center",justifyContent:"center",color:W,fontWeight:900}}>P</span><span style={{flex:1}}><span style={{display:"block",fontSize:15,fontWeight:800,color:W}}>{name}</span><span style={{display:"block",fontSize:11,color:M,marginTop:2}}>{sub||"Profil ansehen"}</span></span><span style={{color:V}}>→</span></Link>:<div style={{background:C,padding:15,border:"1px solid rgba(244,241,235,.1)"}}><p style={{fontSize:15,fontWeight:800,color:W,margin:0}}>Noch nicht angemeldet</p><p style={{fontSize:12.5,color:M,margin:"5px 0 12px"}}>Mit Konto: Rangliste, PingPoints, Spiele und Ergebnisse.</p><div style={{display:"flex",gap:8}}><Link href="/login" onClick={()=>setOpen(false)} style={{flex:1,textAlign:"center",background:V,color:W,padding:"11px 14px",fontSize:13,fontWeight:900,textDecoration:"none"}}>ANMELDEN</Link><Link href="/onboarding" onClick={()=>setOpen(false)} style={{flex:1,textAlign:"center",border:"1px solid rgba(244,241,235,.2)",color:W,padding:"11px 14px",fontSize:13,fontWeight:900,textDecoration:"none"}}>KONTO</Link></div></div>}
 <div style={{background:C,overflow:"hidden",marginTop:10,border:"1px solid rgba(244,241,235,.1)"}}>{authed&&<Link2 href="/profil" label="Profil" icon={<Icon d='<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 4-6 8-6s8 2 8 6"/>'}/>} />}<Link2 href="/rangliste" label="Rangliste" icon={<Icon d='<path d="M5 20v-6M12 20v-11M19 20v-8"/>'}/>} />{authed&&<Link2 href="/matchhistorie" label="Deine Spiele" icon={<Icon d='<path d="M12 8v4l3 2"/><circle cx="12" cy="12" r="9"/>'}/>} />}{authed&&<Link2 href="/pingpoints" label="PingPoints" icon={<Icon d='<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>'}/>} />}<Link2 href="/shop" label="Shop" icon={<Icon d='<circle cx="9" cy="20" r="1.4"/><circle cx="18" cy="20" r="1.4"/><path d="M2.5 3h2l2.2 12.2a1.5 1.5 0 0 0 1.5 1.3h8.4a1.5 1.5 0 0 0 1.5-1.2L21 7H6"/>'}/>} /></div>
 <div style={{fontSize:10,fontWeight:900,color:M,textTransform:"uppercase",letterSpacing:".14em",margin:"22px 4px 8px"}}>Play</div><div style={{background:C,overflow:"hidden",border:"1px solid rgba(244,241,235,.1)"}}><Link2 href="/liga" label="Liga" icon={<Icon d='<path d="M5 20v-4M12 20v-8M19 20v-12"/>'}/>} /><Link2 href="/match" label="Open Game" icon={<Icon d='<ellipse cx="10" cy="9.8" rx="6" ry="5.2"/><path d="M14 13.6 18 17.6"/>'}/>} /><Link2 href="/turniere" label="Turniere" icon={<Icon d='<path d="M3 6h5v5h4M3 16h5v-5M12 11h5"/>'}/>} /><a href={buchenLink()} target="_blank" rel="noopener noreferrer" style={row}><Icon d='<path d="M4 11h16M6 11v6M18 11v6M12 11V6"/>'/><span style={{flex:1,fontSize:14,fontWeight:700,color:W}}>Tisch buchen</span><span style={{color:M}}>↗</span></a></div>{authed&&<button onClick={logout} style={{width:"100%",marginTop:20,background:"transparent",border:"1px solid rgba(244,241,235,.18)",color:W,padding:12,fontSize:12,fontWeight:800,cursor:"pointer"}}>ABMELDEN</button>}</div></div>}</>
}