"use client"
import { useEffect, useState, useCallback } from "react"
import { createClient } from "@/lib/supabase/client"
import Link from "next/link"
import BottomNav from "@/app/components/BottomNav"
import { useRouter } from "next/navigation"
import { OG_PREIS_CHF, OG_STORNO_STUNDEN } from "@/lib/opengames"

const V="#8C3DFF", B="#080808", P="#F4F1EB", MUT="#8e8b87", LINE="#292929"
function whenLabel(date:string|null,hour:number|null){if(!date)return hour!=null?`${String(hour).padStart(2,"0")}:00`:"Zeit offen";const d=new Date(`${date}T12:00:00`);return `${d.toLocaleDateString("de-CH",{weekday:"short",day:"numeric",month:"short"})}${hour!=null?` · ${String(hour).padStart(2,"0")}:00`:""}`}
type Player={user_id:string;name:string;elo:number;level:string}
type Game={id:string;created_by:string;location_name:string;date:string|null;start_hour:number|null;duration_minutes:number;max_players:number;current_players:number;price_per_player:number;is_official?:boolean;level:string;status:string;notes:string|null;created_at:string;players:Player[]}

export default function MatchPage(){
 const router=useRouter(); const [games,setGames]=useState<Game[]>([]); const [userId,setUserId]=useState<string|null>(null); const [myGame,setMyGame]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [joining,setJoining]=useState<string|null>(null); const [error,setError]=useState(""); const [joinError,setJoinError]=useState(""); const [infoOpen,setInfoOpen]=useState(false)
 const load=useCallback(async()=>{setError("");try{const sb=createClient();const{data:{user}}=await sb.auth.getUser();setUserId(user?.id||null);const res=await fetch("/api/match");const json=await res.json();const list:Game[]=json.matches||[];setGames(list);setMyGame(list.find(g=>g.created_by===user?.id)?.id||null)}catch{setError("Spiele konnten nicht geladen werden")}finally{setLoading(false)}},[])
 useEffect(()=>{load()},[load])
 async function join(id:string){setJoining(id);setJoinError("");const res=await fetch(`/api/match/${id}/join`,{method:"POST"});if(res.ok)router.push(`/match/${id}`);else{const j=await res.json();setJoinError(j.error||"Fehler beim Beitreten");setJoining(null)}}
 async function cancel(id:string){await fetch(`/api/match/${id}/cancel`,{method:"POST"});load()}
 const offizielle=games.filter(g=>g.is_official); const eigene=games.filter(g=>!g.is_official)
 return <main style={{minHeight:"100vh",background:B,color:P,paddingBottom:105}}><div style={{maxWidth:560,margin:"0 auto"}}>
  <section style={{padding:"34px 20px 28px",borderBottom:`1px solid ${LINE}`}}><div style={{fontSize:10,fontWeight:900,letterSpacing:".18em",color:V,marginBottom:16}}>PLAY</div><h1 style={{fontFamily:"Impact,Arial Narrow,sans-serif",fontSize:"clamp(54px,15vw,82px)",fontWeight:400,lineHeight:.86,margin:0}}>JUST<br/>PLAY.</h1><div style={{width:70,height:4,background:V,margin:"18px 0"}}/><p style={{maxWidth:390,color:"#aaa",fontSize:14,lineHeight:1.5,margin:0}}>Komm alleine. Triff andere. Spiel Ping Pong. Bei Open Games ist jeder willkommen.</p></section>
  <section style={{padding:"25px 20px 10px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline"}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".14em",color:V}}>OPEN GAMES</div><h2 style={{fontFamily:"Impact,Arial Narrow,sans-serif",fontSize:32,fontWeight:400,margin:"5px 0 0"}}>KOMM VORBEI.<br/>SPIEL MIT.</h2></div><button onClick={()=>setInfoOpen(v=>!v)} style={{background:"none",border:0,color:V,fontWeight:900,fontSize:11,cursor:"pointer"}}>SO GEHT'S {infoOpen?"↑":"↓"}</button></div>
   {infoOpen&&<div style={{marginTop:18,borderTop:`1px solid ${LINE}`}}>{[["01","Abend wählen","Festen Open-Game-Abend auswählen."],["02","Platz sichern",`CHF ${OG_PREIS_CHF} für 4 Stunden. Absage bis ${OG_STORNO_STUNDEN} h vorher.`],["03","Spielen","Vor Ort gegen andere spielen und Resultate eintragen."]].map(x=><div key={x[0]} style={{display:"grid",gridTemplateColumns:"42px 1fr",gap:10,padding:"14px 0",borderBottom:`1px solid ${LINE}`}}><b style={{color:V}}>{x[0]}</b><div><b>{x[1]}</b><div style={{color:MUT,fontSize:12,marginTop:3}}>{x[2]}</div></div></div>)}</div>}
  </section>
  <section style={{padding:"10px 20px 28px"}}>{loading?<div style={{padding:"35px 0",color:MUT}}>Open Games werden geladen …</div>:error?<div style={{padding:"30px 0"}}><p style={{color:MUT}}>{error}</p><button onClick={load} style={{background:V,color:P,border:0,padding:"12px 18px",fontWeight:900}}>NOCHMALS</button></div>:offizielle.length===0?<div style={{borderTop:`1px solid ${LINE}`,padding:"20px 0",color:MUT}}>Aktuell keine offiziellen Open Games.</div>:offizielle.slice(0,14).map(g=>{const frei=Math.max(0,g.max_players-g.current_players),drin=g.players.some(p=>p.user_id===userId),d=g.date?new Date(`${g.date}T12:00:00`):null,heute=d&&d.toDateString()===new Date().toDateString(),day=heute?"HEUTE":d?d.toLocaleDateString("de-CH",{weekday:"short",day:"numeric",month:"short"}).toUpperCase():"—";return <Link key={g.id} href={`/match/${g.id}`} style={{display:"grid",gridTemplateColumns:"70px 1fr auto",gap:14,alignItems:"center",color:P,textDecoration:"none",borderTop:`1px solid ${LINE}`,padding:"18px 0"}}><div><b style={{display:"block",fontSize:10,color:V}}>{day}</b><strong style={{fontSize:21}}>{String(g.start_hour??19).padStart(2,"0")}:00</strong></div><div><strong style={{fontSize:17}}>{g.location_name}</strong><div style={{fontSize:11,color:MUT,marginTop:5}}>Level {g.level} · CHF {g.price_per_player||OG_PREIS_CHF}</div><div style={{fontSize:12,color:drin?V:frei?P:MUT,marginTop:5,fontWeight:800}}>{drin?"DU BIST DABEI ✓":frei?`${frei} ${frei===1?"PLATZ":"PLÄTZE"} FREI`:"AUSGEBUCHT"}</div></div><b style={{color:V,fontSize:20}}>→</b></Link>})}</section>
  <section style={{background:P,color:B,padding:"30px 20px"}}><div style={{fontSize:10,fontWeight:900,letterSpacing:".14em",color:"#6425b8"}}>COMMUNITY</div><h2 style={{fontFamily:"Impact,Arial Narrow,sans-serif",fontSize:34,fontWeight:400,lineHeight:.95,margin:"8px 0 18px"}}>DEIN SPIEL.<br/>DEINE LEUTE.</h2>{eigene.length===0?<><p style={{color:"#666",fontSize:13,lineHeight:1.5}}>Kein passendes Open Game? Erstelle selbst ein Spiel und finde Mitspieler.</p><Link href="/match/create" style={{display:"block",marginTop:18,borderTop:"1px solid #bbb",padding:"16px 0",color:B,textDecoration:"none",fontWeight:900}}>SPIEL ERSTELLEN <span style={{float:"right",color:"#6425b8"}}>→</span></Link></>:<>{myGame&&<button onClick={()=>cancel(myGame)} style={{background:"none",border:0,borderBottom:"1px solid #999",padding:"0 0 4px",fontWeight:800,cursor:"pointer",marginBottom:12}}>Mein Spiel löschen</button>}{eigene.map(g=>{const isMe=g.created_by===userId,joined=g.players.some(p=>p.user_id===userId),host=g.players.find(p=>p.user_id===g.created_by)||g.players[0],full=g.current_players>=g.max_players;return <div key={g.id} style={{borderTop:"1px solid #bbb",padding:"17px 0"}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong>{host?.name||"Spieler"}</strong><div style={{fontSize:12,color:"#666",marginTop:4}}>{g.location_name} · {whenLabel(g.date,g.start_hour)} · Level {g.level}</div>{g.notes&&<div style={{fontSize:12,color:"#666",marginTop:5}}>{g.notes}</div>}</div><b>{g.current_players}/{g.max_players}</b></div>{isMe||joined?<Link href={`/match/${g.id}`} style={{display:"block",color:"#6425b8",fontWeight:900,textDecoration:"none",marginTop:12}}>{isMe?"DEIN SPIEL ANSEHEN":"DU BIST DABEI →"}</Link>:full?<div style={{marginTop:12,color:"#777",fontWeight:800}}>VOLL</div>:<button onClick={()=>join(g.id)} disabled={joining===g.id} style={{background:"none",border:0,padding:0,color:"#6425b8",fontWeight:900,cursor:"pointer",marginTop:12}}>{joining===g.id?"TRITT BEI …":"MITSPIELEN →"}</button>}</div>})}<Link href="/match/create" style={{display:"block",borderTop:"1px solid #bbb",padding:"16px 0",color:B,textDecoration:"none",fontWeight:900}}>WEITERES SPIEL ERSTELLEN <span style={{float:"right",color:"#6425b8"}}>→</span></Link></>}</section>
 </div>{joinError&&<div style={{position:"fixed",bottom:78,left:12,right:12,maxWidth:520,margin:"auto",padding:"12px 18px",background:"#b91c1c",color:"#fff",textAlign:"center",fontSize:13,fontWeight:800,zIndex:200}}>{joinError}</div>}<BottomNav/></main>
}
