"use client"
import { useEffect, useState, useCallback } from "react"
import { useRouter } from "next/navigation"
import BottomNav from "@/app/components/BottomNav"

const BLACK="#080808", OFF="#F4F1EB", V="#8C3DFF", MUT="rgba(244,241,235,.55)
type Notif={id:string;type:string;title:string;body:string|null;link:string|null;read_at:string|null;created_at:string}
function seit(iso:string){const s=Math.floor((Date.now()-new Date(iso).getTime())/1000);if(s<60)return"gerade eben";if(s<3600)return`vor ${Math.floor(s/60)} Min`;if(s<86400)return`vor ${Math.floor(s/3600)} Std`;if(s<172800)return"gestern";return`vor ${Math.floor(s/86400)} Tagen`}

export default function BenachrichtigungenPage(){
 const router=useRouter();const [list,setList]=useState<Notif[]>([]);const [loading,setLoading]=useState(true)
 const laden=useCallback(async()=>{try{const r=await fetch("/api/notifications",{cache:"no-store"});if(r.ok){const j=await r.json();setList(j.notifications||[])}}catch{}setLoading(false)},[])
 useEffect(()=>{laden()},[laden])
 async function openNotif(n:Notif){if(!n.read_at){setList(v=>v.map(x=>x.id===n.id?{...x,read_at:new Date().toISOString()}:x));try{await fetch("/api/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:n.id})})}catch{}}if(n.link)router.push(n.link)}
 async function readAll(){setList(v=>v.map(n=>({...n,read_at:n.read_at||new Date().toISOString()})));try{await fetch("/api/notifications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})})}catch{}}
 const unread=list.some(n=>!n.read_at)
 return <main style={{minHeight:"100vh",background:BLACK,color:OFF,padding:"20px 16px 110px"}}><div style={{maxWidth:520,margin:"0 auto"}}><button onClick={()=>router.back()} style={{border:0,background:"transparent",color:"rgba(244,241,235,.65)",padding:0,fontFamily:"inherit",fontWeight:700,cursor:"pointer"}}>← Zurück</button><header style={{margin:"28px 0 22px"}}><div style={{fontSize:10,fontWeight:900,letterSpacing:".2em",color:V,marginBottom:7}}>PLAYER</div><h1 style={{fontSize:"clamp(34px,9vw,52px)",lineHeight:.92,letterSpacing:"-.035em",fontWeight:900,margin:0}}>WHAT&apos;S NEW.</h1><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:15}}><p style={{margin:0,fontSize:13,color:MUT}}>Einladungen, Resultate und Updates.</p>{unread&&<button onClick={readAll} style={{border:0,background:"transparent",color:V,fontWeight:900,fontSize:11,fontFamily:"inherit",cursor:"pointer"}}>ALLE GELESEN</button>}</div></header>{loading?<p style={{color:MUT,padding:"40px 0"}}>Lädt …</p>:list.length===0?<div style={{borderTop:"1px solid rgba(244,241,235,.14)",padding:"34px 0",color:MUT}}>Noch keine Benachrichtigungen.</div>:list.map((n,i)=><button key={n.id} onClick={()=>openNotif(n)} style={{width:"100%",display:"flex",gap:13,alignItems:"flex-start",textAlign:"left",padding:"16px 0",border:0,borderTop:`1px solid rgba(244,241,235,${i===0?".20":".10"})`,background:"transparent",color:OFF,fontFamily:"inherit",cursor:n.link?"pointer":"default"}}><span style={{width:9,height:9,borderRadius:"50%",background:n.read_at?"rgba(244,241,235,.18)":V,marginTop:5,flex:"0 0 9px"}}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:n.read_at?700:900,lineHeight:1.3}}>{n.title}</div>{n.body&&<div style={{fontSize:12.5,color:"rgba(244,241,235,.62)",marginTop:4,lineHeight:1.45}}>{n.body}</div>}<time style={{fontSize:10.5,color:MUT,display:"block",marginTop:6}}>{seit(n.created_at)}</time></div>{n.link&&<span style={{color:V,fontWeight:900}}>→</span>}</button>)}</div><BottomNav/></main>
}