"use client"
import { useEffect, useState, useCallback, use } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import BottomNav from "@/app/components/BottomNav"
import { BG, CARD, CELL, W, MUT, GREEN, DANGER, cardPad, cell, btn, btnGhost, btnDanger, levelBadge, ratingLabel, h1, body, backLink } from "@/app/theme"
import { entryQrFor, weekdayOf } from "@/lib/opengames"

const M=MUT, B=CELL, G=GREEN
const V="#8C3DFF", OFF="#F4F1EB", BLACK="#080808"

function qrImFenster(dateStr: string): boolean { const now=new Date(); const ev=new Date(`${dateStr}T00:00:00`); return now.getFullYear()===ev.getFullYear()&&now.getMonth()===ev.getMonth()&&now.getDate()===ev.getDate()&&now.getHours()<22 }
function whenLabel(date:string|null,hour:number|null,dur:number){const t=hour!=null?`${String(hour).padStart(2,"0")}:00`:null;if(!date)return t?`heute · ${t}`:"Zeit offen";const d=new Date(date).toLocaleDateString("de-CH",{weekday:"long",day:"numeric",month:"long"});return `${d}${t?` · ${t}`:""} · ${dur}min`}

type Player={user_id:string;name:string;elo:number;level:string;is_creator:boolean}
type Game={id:string;created_by:string;location_name:string;date:string|null;start_hour:number|null;duration_minutes:number;max_players:number;current_players:number;price_per_player:number;level:string;status:string;notes:string|null;is_official?:boolean;kind?:string;winner_id?:string|null;entered_by?:string|null;sets?:Array<{p1:number;p2:number}>|null}
type Data={game:Game;players:Player[];userId:string|null;isCreator:boolean;isJoined:boolean}
type Friend={id:string;name:string;elo?:number;level?:string;avatar_url?:string|null}

export default function MatchDetailPage({params}:{params:Promise<{id:string}>}){
 const {id:matchId}=use(params);const router=useRouter();const [data,setData]=useState<Data|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [err,setErr]=useState("");const [myS,setMyS]=useState(0);const [oppS,setOppS]=useState(0);const [ppBalance,setPpBalance]=useState(0);const [inviteOpen,setInviteOpen]=useState(false);const [friends,setFriends]=useState<Friend[]>([]);const [inviteLoading,setInviteLoading]=useState(false);const [invited,setInvited]=useState<Record<string,boolean>>({})
 const load=useCallback(async()=>{const res=await fetch(`/api/match/${matchId}`);if(res.ok)setData(await res.json());try{const pr=await fetch("/api/pingpoints");if(pr.ok){const pj=await pr.json();setPpBalance(pj.balance??0)}}catch{}setLoading(false)},[matchId]);useEffect(()=>{load()},[load])
 async function join(){setBusy(true);setErr("");const r=await fetch(`/api/match/${matchId}/join`,{method:"POST"});if(!r.ok){const j=await r.json();setErr(j.error||"Fehler")}await load();setBusy(false)}
 async function platzKaufen(redeem=false){setBusy(true);setErr("");try{const r=await fetch(`/api/match/${matchId}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({redeem})});if(r.status===401){router.push("/login");return}const j=await r.json().catch(()=>({}));if(j.needsOnboarding){router.push("/onboarding");return}if(j.gratis){await load();setBusy(false);return}if(!r.ok||!j.url){setErr(j.error||"Bezahlung konnte nicht geöffnet werden — melde dich bei uns.");setBusy(false);return}window.location.href=j.url}catch{setErr("Bezahlung konnte nicht geöffnet werden");setBusy(false)}}
 async function leave(){setBusy(true);setErr("");const r=await fetch(`/api/match/${matchId}/leave`,{method:"POST"});if(!r.ok){const j=await r.json();setErr(j.error||"Fehler")}await load();setBusy(false)}
 async function del(){setBusy(true);await fetch(`/api/match/${matchId}/cancel`,{method:"POST"});router.push("/match")}
 async function sendResult(action:"enter"|"confirm"){setBusy(true);setErr("");const r=await fetch(`/api/match/${matchId}/result`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,my_sets:myS,opp_sets:oppS})});if(r.status===401){window.location.href="/login";return}if(!r.ok){const j=await r.json().catch(()=>({}));setErr(j.error||"Fehler")}await load();setBusy(false)}
 async function openInvites(){setInviteOpen(true);if(friends.length)return;setInviteLoading(true);try{const r=await fetch("/api/friends");if(r.ok){const j=await r.json();setFriends(j.friends||[])}}finally{setInviteLoading(false)}}
 async function inviteFriend(id:string){setInvited(v=>({...v,[id]:true}));const r=await fetch(`/api/match/${matchId}/invite`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:id})});if(!r.ok){setInvited(v=>({...v,[id]:false}));const j=await r.json().catch(()=>({}));setErr(j.error||"Einladung konnte nicht gesendet werden")}}
 if(loading||!data)return <main style={{minHeight:"100vh",background:BG,display:"flex",alignItems:"center",justifyContent:"center"}}><p style={body}>Lädt …</p><BottomNav/></main>
 const {game:g,players,isCreator,isJoined,userId}=data;const full=g.current_players>=g.max_players;const slots=Array.from({length:g.max_players});const cancelled=g.status==="cancelled";const duo=players.length===2;const opponent=players.find(p=>p.user_id!==userId);const enteredByMe=g.entered_by===userId;const iWon=g.winner_id===userId;const sets=g.sets||[];const mySets=sets.filter(s=>(g.entered_by===userId?s.p1>s.p2:s.p2>s.p1)).length;const oppSets=sets.length-mySets
 const aktionBlock=isCreator?(confirmDelete?<div style={{...cardPad,padding:"14px 16px"}}><p style={{fontSize:13,color:DANGER,fontWeight:700,marginBottom:10}}>Spiel wirklich löschen?</p><div style={{display:"flex",gap:8}}><button onClick={()=>setConfirmDelete(false)} style={{...btnGhost,flex:1,padding:10,fontSize:13}}>Abbrechen</button><button onClick={del} disabled={busy} style={{...btnDanger,flex:1,padding:10,fontSize:13}}>{busy?"…":"Ja, löschen"}</button></div></div>:<button onClick={()=>setConfirmDelete(true)} style={{...btnGhost,width:"100%",padding:13,fontSize:13}}>Spiel löschen</button>):isJoined?<><button onClick={leave} disabled={busy} style={{...btnGhost,width:"100%",padding:14}}>{busy?"…":g.is_official&&g.price_per_player>0?"Absagen · Geld zurück":"Doch nicht · Platz freigeben"}</button>{g.is_official&&g.price_per_player>0&&<p style={{...body,textAlign:"center",marginTop:8,fontSize:12.5}}>Absage bis 24 h vorher — Geld zurück.</p>}</>:full?<div style={{...cardPad,textAlign:"center"}}><p style={{fontSize:14,fontWeight:700,color:M}}>Ausgebucht</p></div>:g.is_official&&g.price_per_player>0?<><button onClick={()=>platzKaufen(false)} disabled={busy} style={{...btn,width:"100%",padding:16,fontSize:15.5}}>{busy?"…":`Platz sichern · CHF ${g.price_per_player}`}</button>{ppBalance>=g.price_per_player&&<button onClick={()=>platzKaufen(true)} disabled={busy} style={{...btnGhost,width:"100%",padding:14,marginTop:8,fontSize:14}}>{busy?"…":`Mit PingPoints buchen · ${g.price_per_player} Punkte`}</button>}<p style={{...body,textAlign:"center",marginTop:8,fontSize:12.5}}>{(g.duration_minutes/60).toLocaleString("de-CH")} Std · Absage bis 24 h vorher, Geld zurück.</p></>:<button onClick={join} disabled={busy} style={{...btn,width:"100%",padding:15,fontSize:15}}>{busy?"Trete bei …":"Mitspielen →"}</button>
 return <main style={{minHeight:"100vh",background:BLACK,padding:"20px 16px 100px"}}><div style={{maxWidth:480,margin:"0 auto"}}><Link href={g.kind==="training"?"/training":"/match"} style={backLink}>← {g.kind==="training"?"Training":"Open Games"}</Link><div style={{margin:"24px 0 20px"}}><div style={{fontSize:10,fontWeight:900,letterSpacing:".18em",color:V,textTransform:"uppercase",marginBottom:7}}>{g.kind==="training"?"Training":"Open Game"}</div><h1 style={{...h1,fontSize:34,lineHeight:.95,margin:"0 0 12px",color:OFF,textAlign:"left"}}>{g.kind==="training"?`TRAINING ${g.location_name}`:g.is_official?g.location_name.toUpperCase():"JUST PLAY."}</h1><p style={{...body,color:"rgba(244,241,235,.7)"}}>{whenLabel(g.date,g.start_hour,g.duration_minutes)}{g.is_official?"":` · ${g.location_name}`}</p><p style={{...body,color:g.price_per_player>0?"rgba(244,241,235,.65)":V,marginTop:4}}>{g.price_per_player>0?`CHF ${g.price_per_player} pro Person`:"Gratis"}</p></div>
 {cancelled?<div style={{...cardPad,textAlign:"center"}}><p style={{fontSize:14,fontWeight:700,color:DANGER}}>Dieses Spiel wurde abgesagt</p></div>:<><div style={{marginBottom:10}}>{aktionBlock}</div>{userId&&g.kind!=="training"&&<button onClick={openInvites} style={{width:"100%",padding:14,marginBottom:12,border:`1px solid ${V}`,background:"transparent",color:OFF,fontWeight:900,letterSpacing:".04em",fontFamily:"inherit",cursor:"pointer"}}>FREUNDE EINLADEN</button>}
 {g.is_official&&isJoined&&g.date&&entryQrFor(g.location_name,weekdayOf(g.date))&&(qrImFenster(g.date)?<div style={{...cardPad,marginBottom:12,textAlign:"center"}}><p style={{fontSize:11,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase",color:V,marginBottom:10}}>Dein Eintritt · {g.location_name}</p><div style={{position:"relative",width:200,height:200,margin:"0 auto",background:"#fff",borderRadius:16,overflow:"hidden"}}><img src={entryQrFor(g.location_name,weekdayOf(g.date!))!} alt="Zutritts-QR" style={{width:"100%",height:"100%",objectFit:"contain"}}/></div><p style={{...body,marginTop:10}}>An der Tür scannen — gültig bis 22 Uhr.</p></div>:<div style={{...cardPad,marginBottom:12,textAlign:"center"}}><p style={{fontSize:11,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase",color:V,marginBottom:6}}>Dein Eintritt · {g.location_name}</p><p style={body}>Dein Zutritts-QR erscheint hier <b style={{color:W}}>am Termin-Tag</b> — gültig bis 22 Uhr.</p></div>)}
 <div style={{...cardPad,marginBottom:12}}><p style={{...body,marginBottom:12}}>{g.current_players}/{g.max_players} Spieler dabei</p><div style={{display:"flex",flexDirection:"column",gap:8}}>{slots.map((_,i)=>{const p=players[i];return <div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"10px 12px",...cell}}><div style={{width:36,height:36,borderRadius:"50%",background:p?V:"#181C22",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,color:p?OFF:M}}>{p?(p.name||"").split(/\s+/).map(w=>w[0]).join("").slice(0,2).toUpperCase():"+"}</div>{p?<div style={{flex:1}}><span style={{fontSize:14,fontWeight:700,color:W}}>{p.name}</span>{p.is_creator&&<span style={{fontSize:9,color:"rgba(255,255,255,.7)",marginLeft:6}}>Host</span>}<p style={{fontSize:12,color:M,fontWeight:500}}>Rating {ratingLabel(p.elo)} · {p.level}</p></div>:<span style={{flex:1,...body}}>Freier Platz</span>}</div>})}</div></div>
 {g.notes&&<div style={{...cardPad,padding:"12px 16px",marginBottom:12}}><p style={{...body,fontStyle:"italic"}}>&quot;{g.notes}&quot;</p></div>}{err&&<p style={{color:DANGER,fontSize:13,marginBottom:12,textAlign:"center"}}>{err}</p>}
 {isJoined&&duo&&!cancelled&&(g.status==="confirmed"?<div style={{...cardPad,padding:"18px 16px",textAlign:"center",marginBottom:12}}><p style={{fontSize:11,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase",color:M}}>Gewertet</p><p style={{fontSize:20,fontWeight:900,color:V}}>{iWon?"Sieg":"Niederlage"}</p><p style={body}>ELO und Rangliste sind aktualisiert.</p></div>:g.status==="p1_entered"?(enteredByMe?<div style={{...cardPad,padding:16,textAlign:"center",marginBottom:12}}><p style={{fontSize:13,fontWeight:700,color:W}}>Ergebnis eingetragen</p><p style={body}>{opponent?.name||"Dein Gegner"} muss noch bestätigen.</p></div>:<div style={{...cardPad,padding:18,marginBottom:12,textAlign:"center"}}><p style={{fontWeight:800,color:W}}>Ergebnis bestätigen</p><p style={body}>{opponent?.name||"Dein Gegner"} hat eingetragen: <strong style={{color:W}}>{mySets}:{oppSets}</strong> für dich</p><button onClick={()=>sendResult("confirm")} disabled={busy} style={{...btn,width:"100%",padding:14}}>{busy?"…":"Bestätigen ✓"}</button></div>):<div style={{...cardPad,padding:18,marginBottom:12}}><p style={{fontSize:14,fontWeight:800,color:W,textAlign:"center"}}>Schon gespielt?</p><p style={{...body,textAlign:"center",marginBottom:16}}>Trag die Sätze ein — danach zählt&apos;s für ELO &amp; Rang.</p><div style={{display:"flex",justifyContent:"center",gap:14,alignItems:"center"}}><button onClick={()=>setMyS(Math.max(0,myS-1))} style={btnGhost}>−</button><b style={{fontSize:28,color:V}}>{myS} : {oppS}</b><button onClick={()=>setOppS(Math.min(7,oppS+1))} style={btnGhost}>+</button></div><button onClick={()=>sendResult("enter")} disabled={busy||myS===oppS} style={{...btn,width:"100%",padding:14,marginTop:18,opacity:myS===oppS?.5:1}}>Ergebnis absenden</button></div>)}</>}
 </div><BottomNav/>{inviteOpen&&<div onClick={()=>setInviteOpen(false)} style={{position:"fixed",inset:0,zIndex:450,background:"rgba(0,0,0,.72)",display:"flex",alignItems:"flex-end",justifyContent:"center"}}><div onClick={e=>e.stopPropagation()} style={{width:"100%",maxWidth:480,maxHeight:"72vh",overflowY:"auto",background:OFF,color:BLACK,padding:"20px 18px 28px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div><div style={{fontSize:10,fontWeight:900,letterSpacing:".16em",color:V}}>OPEN GAME</div><div style={{fontSize:24,fontWeight:900}}>Freunde einladen</div></div><button onClick={()=>setInviteOpen(false)} style={{border:0,background:"transparent",fontSize:24,cursor:"pointer"}}>×</button></div>{inviteLoading?<p>Lädt …</p>:friends.length===0?<p style={{opacity:.65}}>Du hast noch keine bestätigten Freunde im Player.</p>:friends.map(f=><div key={f.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 0",borderTop:"1px solid rgba(8,8,8,.12)"}}><div style={{width:38,height:38,borderRadius:"50%",background:BLACK,color:OFF,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900}}>{(f.name||"?").slice(0,1).toUpperCase()}</div><div style={{flex:1}}><div style={{fontWeight:900}}>{f.name}</div>{f.level&&<div style={{fontSize:12,opacity:.55}}>{f.level}</div>}</div><button disabled={invited[f.id]} onClick={()=>inviteFriend(f.id)} style={{border:0,background:invited[f.id]?BLACK:V,color:OFF,padding:"10px 12px",fontWeight:900,fontFamily:"inherit",cursor:invited[f.id]?"default":"pointer"}}>{invited[f.id]?"EINGELADEN":"EINLADEN"}</button></div>)}</div></div>}</main>
}